### PR TITLE
Fix form styles

### PR DESCRIPTION
**Pull request by wbprice**

### CODE REVIEW

**Comment by tjwebb** [comment]
@wbprice weird, I have no idea why CI is failing.

**Comment by wbprice** [comment]
```
Problem accessing /uploads/form/v2/undefined/undefined.
```
It would appear that `portalId` and `formId` in `ContactService` are undefined in the test.

**Comment by wbprice** [comment]
@tjwebb Are these env vars defined in CI?
```
  hubspot: {
    hubspotKey: process.env.HUBSPOT_API_KEY,
    portalId: process.env.HUBSPOT_PORTAL_ID,
    formId: process.env.HUBSPOT_FORM_ID
  }
```

**Comment by tjwebb** [comment]
Yea, those are set correctly, and nothing has changed since the previous passing builds. I'll test locally.

**Review by tjwebb — COMMENTED** [review]
lgtm

**Pull request merged**
